### ISSUE TITLE
Input mapper throws error about undefined defaultAction property.

### ISSUE THREAD

**Issue by the-t-in-rtf** [fluid-lab/gamepad-navigator#11]
I just saw an error thrown on [this line in the input mapper](https://github.com/fluid-lab/gamepad-navigator/blob/master/src/js/content_scripts/input-mapper.js#L214) in my instance of Chrome.

```
Uncaught TypeError: Cannot read property 'defaultAction' of undefined
```

![Screenshot 2020-06-25 at 10 51 09](https://user-images.githubusercontent.com/5765222/85689131-a96b7280-b6d2-11ea-88ee-fdf4a64080a8.png)

**Comment by dmahajan980** [comment]
This has been generated due to the presence of button 17 (or any other button whose configurations isn't specified in the [map](https://github.com/fluid-lab/gamepad-navigator/blob/master/src/js/content_scripts/input-mapper.js#L22) of `inputMapper` component). I'll update the conditions so that we don't face any similar errors in the future.

**Comment by dmahajan980** [comment]
@the-t-in-rtf since this issue has been fixed with the latest pull, it would be safe to close it.
