### ISSUE TITLE
Add support for re-configuring gamepad input's sensitivity

### ISSUE THREAD

**Issue by dmahajan980** [fluid-lab/gamepad-navigator#59]
As per the discussion during the Design Crit, there might be cases where people with limited mobility or disability might not be able to press the gamepad inputs (buttons, triggers, thumbsticks) to the full extent or above the `cutoffValue` barrier that we kept. There should be some way to change the sensitivity of the gamepad inputs by providing users the flexibility to vary the `cutoffValue` option.

**Comment by duhrer** [comment]
As part of this, it would also be good to move this support somewhere more central.  At the moment it's applied fairly deep in a few of the thumb stick actions, i.e. the value is analysed for direction and passed to the direction-specific function, which checks the cutoff.

This could be moved to the action launcher, for example, and then we would have cutoff guards for the triggers as well.

I also think we need to consider either using this cutoff or perhaps a second cutoff to reduce "jitter" when holding down an axis or analog button.  As an example:

1. Configure the triggers to navigate to the previous/next focusable item on the page.
2. Hold each trigger all the way down, note the lack of repeated navigation.
3. Hold each trigger partially down or slowly squeeze and release the trigger.

You can get to a state where the control repeats because of the small variations in value, where it would not repeat when holding a digital button.

This could be avoided by checking to see if the newValue is far enough from the old value, although that does mean that the cutoff would act more like "indexing", i.e. if the cutoff is less than .51, you would basically have more than one point at which the cutoff is reached.

I need to review this more with regards to our polling strategy for repeatable controls as well, to ensure that we aren't repeating faster than the speed factor simply by virtue of the "jitter" making the control value appear like it's changed.

**Comment by duhrer** [comment]
Another idea I had is to have per-control cutoff values and make sensible defaults.  This is something that could be applied when polling the gamepads.  It gets a little more difficult to apply within the action unless we add it as yet another parameter for all actions.

**Comment by duhrer** [comment]
Although I'm still thinking about per-control cutoffs, the new settings panel ads a general preference to control the cutoff for all inputs.
