### ISSUE TITLE
Add feature to view the current configuration

### ISSUE THREAD

**Issue by dmahajan980** [fluid-lab/gamepad-navigator#62]
Given that the navigator currently supports a good number of navigation features, it might be difficult to remember the whole configuration. Even later on, when we add support for chording and new navigation features, it'd become more challenging to remember what each keypress and key combination does. There should be some way to review the gamepad configuration whenever the user wants.

One strategy would be to display a map on the screen by the use of the "badge icon" button. However, we should also look into other ways and strategies to accoplish the goal.

**Comment by Parthkhandelwal0** [comment]
hey @dmahajan980 i would like to contribute to this issue, I am pretty 
new to this project can help me get started?

**Comment by dmahajan980** [comment]
Hi @Parthkhandelwal0, you can check out the instructions [here](https://github.com/fluid-lab/gamepad-navigator/blob/main/CONTRIBUTING.md).

Once you are done with the initial steps (learning Infusion, familiarizing yourself with source code), you can discuss your approaches and solutions with us (me and @the-t-in-rtf).

**Comment by Parthkhandelwal0** [comment]
i familiarized myself with the code, but when the extension is clicked it already shows all the functions and the corresponding keys, what more should be added?

**Comment by the-t-in-rtf** [comment]
Sorry for the delay in responding over the holidays.

Right now, in order to see what each button does, you'd have to navigate through the whole set of controls.  What @dmahajan980 and I have discussed is making it possible to see at a glance all of the configured controls and actions.

One approach used by many video game help screens is to make a large diagram that labels each active control.  This would mostly work for the extension as it current stands, as individual buttons and axes generally map to a single function.  However, as @dmahajan980 mentioned, we are discussing adding support for complex arrangements like chording and long presses, which would be difficult to represent on a single diagram.

My current thinking is that we would be better off having a summary view where the actions that are bound to controls are listed, with a picture of an idealised gamepad next to it.  The buttons / axes bound to an action would be highlighted.

I mocked up a quick demonstration of what I have in mind.

![20210112 Gamepad Configuration Mockup](https://user-images.githubusercontent.com/5765222/104294943-23711680-54c0-11eb-81b4-dce58d1eec1b.png)

That's roughly based on an Xbox One controller, we can use the same approach with the diagram borrowed from the Gamepad API docs, or make.a new "generic" controller icon.  The approach I mocked up was to show all controls and highlight those bound to the action, we could also just show only the controls used for.a given action, this might read better from a distance.

Another approach might be just to show the text of the action and the text of the bound controls on a single summary view.  This approach would be simpler to implement, although it would require some refactoring to move from our current configuration UI to something where you can dynamically add / remove bindings.

**Comment by the-t-in-rtf** [comment]
Just to share a little more thinking, if we choose to represent the "bound" controls visually, we have to consider a few cases:

1. How to represent actions to be taken on a short key press.
2. How to represent actions to be taken on a long key press.
3. How to represent actions bound to one axis on the dpad
4. Same for a thumbstick.
5. How to represent actions (such as scrolling) bound to both axes on the dpad.
6. Same for a thumbstick.
7. How to represent actions bound to a single direction on the dpad.
8. How to represent chording (short presses on multiple buttons).
9. How to represent "long chording" (long presses on multiple buttons).
10. How to represent chording between an axis or analog control and a button, such as a "shift" button that changes the functionality of a thumbstick or trigger.

As this is quite a complex list of things to distinguish visually, I'm thinking that maybe a textual summary of bound actions and controls is the best option.
