### ISSUE TITLE
Onscreen Keyboard

### ISSUE THREAD

**Issue by Gekocaretaker** [fluid-lab/gamepad-navigator#84]
Could there be an onscreen keyboard, for inputs? This way, we don't have to switch to the keyboard whenever we need to type?
Consoles use onscreen keyboards for inputting information.

**Comment by the-t-in-rtf** [comment]
We have been talking about this specifically with regard to #85 (inputting a URL).  In order to use this with things like form inputs, we need to figure out a few things around focus.

If we open our own onscreen keyboard and use focus there to indicate which key will be pressed, does that remove the focus from the form input?  I suspect it would, so we'd have to do something like remember the last focused element and send keyboard events from the onscreen keyboard to that.  This would have the undesirable side-effect of hiding the focused element and interacting poorly when entering text and then navigating away.

One way to avoid this would be to not use focus within the onscreen keyboard, perhaps using a "marker" attribute on the key should be highlighted.

It seems like a good first step to look at pure HTML5/Javascript onscreen keyboards to see if there's anything we can adopt, adapt, or learn from.  @jobara, are you aware of any reasonable browser-based onscreen keyboards?

**Comment by the-t-in-rtf** [comment]
I'm also thinking that we need to decide what keys to reserve for navigation within the onscreen keyboard.  The d-pad keys seem like a good fit for changing position.  For simple use cases, we'd need to reserve a button for clicking a key (perhaps we can reuse the same one that would activate a focused link).

For form inputs, we also need to think about more advanced usage, such as entering capital letters.  One solution would be to have an onscreen "shift" button that only modifies the next key and then turns off, and then a "caps" button that modifies all (letter) keys until it's  turned off.

**Comment by jobara** [comment]
> We have been talking about this specifically with regard to #85 (inputting a URL). In order to use this with things like form inputs, we need to figure out a few things around focus.
> 
> If we open our own onscreen keyboard and use focus there to indicate which key will be pressed, does that remove the focus from the form input? I suspect it would, so we'd have to do something like remember the last focused element and send keyboard events from the onscreen keyboard to that. This would have the undesirable side-effect of hiding the focused element and interacting poorly when entering text and then navigating away.
> 
> One way to avoid this would be to not use focus within the onscreen keyboard, perhaps using a "marker" attribute on the key that should be highlighted.
> 
> It seems like a good first step to look at pure HTML5/Javascript onscreen keyboards to see if there's anything we can adopt, adapt, or learn from. @jobara, are you aware of any reasonable browser-based onscreen keyboards?

@the-t-in-rtf I'm not aware off hand of HTML/JS onscreen keyboards. I did some quick searching and there are some, but they seem to often be tied to specific inputs. 

One thought I have, if the onscreen keyboard will only be used by the gamepad navigator, that you just sort of a have an overlay that is controlled by the gamepad. In this way you don't have to move focus, and you can just use the gamepad's input to modify how the keyboard is presented in order to indicate the selection/actions. You'd have to pay care for how it might interact with ATs though.

**Comment by Gekocaretaker** [comment]
HTML and JavaScript have the ability for you to click on something without focusing on it. This means that you don't need to use button elements or inputs of type button to do this. You can just use div elements to act as buttons, and then send that data to the current input. But when you click on the div, you will need to get the currently selected input, add the clicked character, and then refocus on that input element.
This is just some input of mine.

**Comment by the-t-in-rtf** [comment]
@gekocaretaker, that's roughly what we were proposing in different words.

I  looked at a few onscreen HTML/JS keyboards, most seem less well suited for our purposes, as they are designed for touch, click, and mirroring keystrokes from a physical keyboard.  We might be able to adapt one to add our own listeners and highlighting, but my guess is we'll have to make our own.

I've been looking at keyboards for smart devices and consoles for a bit to get ideas.  Some have niceties like prepending a prefix or appending a domain suffix (.com, .ca, etc.).  Some support a range of special characters in separate views.  Some present the characters in their keyboard layout.  Some present them optimised for the amount of space available (such as the Apple TV's left-right alphabet on top of the screen).

I suspect we'll need a modal or popup to give ourselves enough room and make something visible.

To keep the scope reasonable, we could choose to do a few things:

1. Limit ourselves to A-Z, numbers, period, slash, dash, underscore, colon.
2. Don't support unicode in hostnames.
3. Don't support query strings, as in `http://my.site.com/page?query=this`.
4. Don't support usernames and passwords, as in `https://admin@password:localhost/`
5. Prepend an implied scheme, i.e. `https` if nothing else is specified, so that `wikipedia.org` alone is enough to open that site.  (This is what the search/location bar in Chrome for Android does.)

I need to look at how the omnibar API works, it may be that we can just pass whatever's entered to that, so that we also make it easier to search with a gamepad.

**Comment by duhrer** [comment]
This work has been merged and will be part of the upcoming 1.0 release.
